<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-6T8U07T" failures="3" tests="9" name="testName" time="128.849" errors="0" timestamp="2022-07-28T11:15:48 EET">
  <testcase classname="testCases.TC_CreateNewAccount_001" name="addNewCutomer" time="15.39"/>
  <testcase classname="testCases.TC_Login_002" name="AuthenticateAsNewUser" time="4.317"/>
  <testcase classname="testCases.TC_LoginDataDrivenTest_003" name="AuthenticateAsNewUser" time="4.563">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_LoginDataDrivenTest_003.AuthenticateAsNewUser(TC_LoginDataDrivenTest_003.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AuthenticateAsNewUser -->
  <testcase classname="testCases.TC_LoginDataDrivenTest_003" name="AuthenticateAsNewUser" time="15.977"/>
  <testcase classname="testCases.TC_LoginDataDrivenTest_003" name="AuthenticateAsNewUser" time="7.664">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_LoginDataDrivenTest_003.AuthenticateAsNewUser(TC_LoginDataDrivenTest_003.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AuthenticateAsNewUser -->
  <testcase classname="testCases.TC_LoginDataDrivenTest_003" name="AuthenticateAsNewUser" time="8.056">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_LoginDataDrivenTest_003.AuthenticateAsNewUser(TC_LoginDataDrivenTest_003.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AuthenticateAsNewUser -->
  <testcase classname="testCases.TC_LoginDataDrivenTest_003" name="AuthenticateAsNewUser" time="10.751"/>
  <testcase classname="testCases.TC_SelectProductAndCheckOut_004" name="SelectProductAndCheckout" time="21.896"/>
  <testcase classname="testCases.TC_ValidateOrder_005" name="ValidateOrder" time="11.316"/>
</testsuite> <!-- testName -->
